name: Build and Release

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  release:
    types: [created]

jobs:
  build-and-release:
    name: Build and Release
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.18
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Get dependencies
        run: |
          go get -v -t -d ./...

      - name: Run tests
        run: |
          make test
          bash <(curl -s https://codecov.io/bash)

      - name: Build darwin_amd64
        run: |
          CGO_ENABLED=0 GOOS=darwin GOARCH=amd64 make build

      - name: Build darwin_arm64
        run: |
          CGO_ENABLED=0 GOOS=darwin GOARCH=arm64 make build

      - name: Build linux_amd64
        run: |
          CGO_ENABLED=0 GOOS=linux GOARCH=amd64 make build

      - name: Build linux_arm64
        run: |
          CGO_ENABLED=0 GOOS=linux GOARCH=arm64 make build

      - name: Build windows_amd64
        run: |
          FILEEXT='.exe' CGO_ENABLED=0 GOOS=windows GOARCH=amd64 make build

      - name: Build windows_arm64
        run: |
          FILEEXT='.exe' CGO_ENABLED=0 GOOS=windows GOARCH=arm64 make build

      - name: Publish binaries
        if: github.event_name == 'release'
        uses: skx/github-action-publish-binaries@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: "build/khs_*"
